---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: vcluster
  namespace: whbox-ephemeral
spec:
  interval: 5m0s
  url: https://charts.loft.sh
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: whbox-vcluster-dev
spec:
  releaseName: whbox-vcluster-dev
  chart:
    spec:
      chart: vcluster
      version: "0.17.0"
      interval: 2m
      sourceRef:
        kind: HelmRepository
        name: vcluster
        namespace: whbox-ephemeral
  interval: 1m0s
  values:
    fallbackHostDns: true