demo-web:
  fullnameOverride: 'demo-web-uat'
  image:
    registry: docker.io
    repository: ixxel/demo-web
    tag: latest
  rollouts:
    enabled: false
  gatewayApi:
    enabled: false
    gateway:
      name: wildcard-tls-gateway
      namespace: kube-system
      section: https
    httpRoute:
      hosts:
      - demo-web-uat.k8s-app.gateway.fredcorp.com
      pathType: PathPrefix
      path: /
  # ingress:
  #   enabled: true
  #   className: "cilium"
  #   annotations:
  #     cert-manager.io/cluster-issuer: vault-issuer
  #     cert-manager.io/common-name: 'demo-web.k8s-app.fredcorp.com'
  #   hosts:
  #     - host: 'demo-web.k8s-app.fredcorp.com'
  #       paths:
  #         - path: /
  #           pathType: Prefix
  autoscaling:
    enabled: false
  test: 
    enabled: false