---
name: Promote helm chart
on:
  repository_dispatch:
    types:
      - helm_promotion

permissions: 
  contents: write
  pull-requests: write # Optional, depending on your workflow

jobs:
  helm-promotion:
    name: Promote Helm chart to next environment
    timeout-minutes: 5
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
      name: checkout
    - run: |
        echo "helm chart version : ${{ github.event.client_payload.helm_chart_version }}"
        echo "app version : ${{ github.event.client_payload.app_version }}"
    # - name: Trigger Repository Dispatch for ArgoCD Application Deployment
    #   run: |
    #     curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
    #         -H "Accept: application/vnd.github.v3+json" \
    #         https://api.github.com/repos/${{ github.repository }}/dispatches \
    #         -d '{"event_type": "helm_promotion", "client_payload": {"cluster_name": "${{ github.event.client_payload.cluster_name }}"}}