---
name: Promote image to production
on:
  workflow_dispatch:
  push:
    branches:
    - 'auto/**'

permissions:
  pull-requests: write

jobs:
  auto-pull-request:
    name: Promote image to prod
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      name: checkout

    - name: pull-request
      run: |
        echo -e "${BLUE}[ STEP - CREATING PR ] > Creatin Pull Request with gh CLI${BLANK}"
        echo -e "${CYAN}[ INFO ] > gh version.${BLANK}"
        gh --version

        gh_pr_up() {
          gh pr create "$@" || gh pr edit "$@" 
        }

        gh_pr_up --title "chore: image promotion ${{ github.ref }} into main" \
                 --body ":crown: *An automated PR* - ${{ github.ref }}" \
                 --base "main"
      env:
        GH_TOKEN: ${{ secrets.SUPER_ADMIN_TOKEN }}
        RED: \033[1;31m
        GREEN: \033[1;32m
        YELLOW: \033[1;33m
        BLUE: \033[1;34m
        PURPLE: \033[1;35m
        CYAN: \033[1;36m
        BLANK: \033[0m

    # - uses: repo-sync/pull-request@v2
    #   name: pull-request
    #   with:
    #     destination_branch: "main"
    #     pr_title: "chore: image promotion ${{ github.ref }} into main"
    #     pr_body: ":crown: *An automated PR* - ${{ github.ref }}"
    #     pr_reviewer: "ixxeL2097"
    #     pr_draft: false
    #     github_token: ${{ secrets.SUPER_ADMIN_TOKEN }}
