---
name: Helm Manifests Diff for ArgoCD
on:
  pull_request:
    branches:
      - main

jobs:
  helm-diff:
    runs-on: self-hosted
    steps:
      - name: Checkout PR
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Find modified Chart.yaml files
        id: changed-files
        uses: tj-actions/changed-files@v45
        with:
          files: |
            **/Chart.yaml

      - name: Generate diffs for each Chart
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          # Function to get the latest version matching a pattern
          get_latest_version() {
            local repo=$1
            local chart=$2
            local pattern=$3
            helm search repo $repo/$chart -o json | jq -r ".[].version" | grep "^$pattern" | sort -V | tail -n 1
          }
          mkdir -p target
          mkdir -p source
          echo "CHART_FILES=${ALL_CHANGED_FILES}"
          
          for file in ${ALL_CHANGED_FILES}; do
            echo "Processing $file"
            
            # Get chart directory
            CHART_DIR=$(dirname "$file")
            ENV=$(echo "$CHART_DIR" | awk -F'/' '{print $2}')
            NS=$(echo "$CHART_DIR" | awk -F'/' '{print $4}')

            # Extract info from PR version
            CHART_NAME=$(yq e '.name' "$file")
            CHART_VERSION=$(yq e '.version' "$file")

            echo "chart infos : dir -> $CHART_DIR name -> $CHART_NAME version -> $CHART_VERSION"
            
            for dep in $(yq e -o=j -I=0 '.dependencies[]' "$file")
            do
              echo "$dep" | jq -C
              DEP_NAME=$(echo "$dep" | jq -r '.name')
              DEP_VERSION=$(echo "$dep" | jq -r '.version')
              DEP_REPO=$(echo "$dep" | jq -r '.repository')
              helm repo add "$DEP_NAME" "$DEP_REPO"
            done

            helm repo update
            # Generate PR manifest
            helm dependency update "$CHART_DIR"
            helm template "$CHART_NAME" "$CHART_DIR" > "target/${ENV}_${NS}_${CHART_NAME}_manifest_pr.yaml"
            yq e -C target/${ENV}_${NS}_${CHART_NAME}_manifest_pr.yaml
            
            # Get main branch version and generate manifest
            git checkout origin/main -- "$file"
            MAIN_CHART_VERSION=$(yq e '.version' "$file")
            
            # Process dependencies for main version
            for dep in $(yq e -o=j -I=0 '.dependencies[]' "$file")
            do
              echo "$dep" | jq -C
              DEP_NAME=$(echo "$dep" | jq -r '.name')
              DEP_VERSION=$(echo "$dep" | jq -r '.version')
              DEP_REPO=$(echo "$dep" | jq -r '.repository')
              helm repo add "$DEP_NAME" "$DEP_REPO"
            done
            
            helm dependency update "$CHART_DIR"
            helm template "$CHART_NAME" "$CHART_DIR" > "source/${ENV}_${NS}_${CHART_NAME}_manifest_main.yaml"
            yq e -C source/${ENV}_${NS}_${CHART_NAME}_manifest_main.yaml
          done

      - name: Generate dyff on release
        id: dyff-helm
        run: |
          curl --silent --location https://git.io/JYfAY | sudo bash
          RESULTS=""
          ls -la source
          ls -la target

          for source_file in source/*_manifest_main.yaml
          do

            echo "found $source_file"

            chart_name=$(basename "$source_file" _manifest_main.yaml)

            echo "chart name $chart_name"

            target_file="target/${chart_name}_manifest_pr.yaml"

            echo "target file $target_file"

            if [ -f "$target_file" ]; then
              RESULT=$(dyff between --color on \
                                    --output human \
                                    --truecolor on \
                                    "$source_file" "$target_file")
              echo "${RESULT}"

              CLEANED_RESULT=$(echo "${RESULT}" | sed -r "s/\x1B\[[0-9;]+[mGKFHmsu]//g")
              RESULTS+="${CLEANED_RESULT}"
              RESULTS+="\n\n"
            else
              echo "Target file not found: $target_file"
            fi
          done

          {
            echo 'DYFF_RESULT<<EOF'
            echo -e "${RESULTS}"
            echo EOF
          } >> $GITHUB_OUTPUT

      # - name: Generate dyff on release
      #   id: dyff-helm
      #   uses: ixxeL-DevOps/gha-templates/.github/actions/dyff@main
      #   with:
      #     first-file: temp/pr_manifest_pr.yaml
      #     second-file: temp/main_manifest_main.yaml

      - name: Comment on PR for helm dyff
        uses: actions/github-script@v7
        if: github.event_name == 'pull_request'
        env:
          DYFF_RESULTS: ${{ steps.dyff-helm.outputs.DYFF_RESULT }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `
            #### Dyff helm: \`chart helm dyff\`
            \`\`\`py
            ${process.env.DYFF_RESULTS}
            \`\`\`
            `;

            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: output
            })
