---
name: Helm Manifests Diff - Rendered Manifest (Helmrelease)
on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main
    paths:
      - '**/helmrelease.yaml'
      - '**/helmrelease.yml'

jobs:
  helm-diff-hr:
    runs-on: self-hosted
    steps:
      - name: Checkout PR
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Find modified Chart.yaml files
        id: changed-files
        uses: tj-actions/changed-files@v45
        with:
          files: |
            **/helmrelease.yaml
            **/helmrelease.yml

      - name: Generate diffs for each HelmRelease
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          mkdir -p target
          mkdir -p source
          echo "HELMRELEASE_FILES=${ALL_CHANGED_FILES}"

          for file in ${ALL_CHANGED_FILES}; do
            echo "Processing $file"
            CHART_DIR=$(dirname "$file")
            CHART_NAME=$(yq e 'select(document_index == 1).spec.chart.spec.chart' $file)
            CHART_VERSION=$(yq e 'select(document_index == 1).spec.chart.spec.version' $file)
            REPO_NAME=$(yq e 'select(document_index == 1).spec.chart.spec.sourceRef.name' $file)
            REPO_URL=$(yq e 'select(document_index == 0).spec.url' $file)

            echo "chart infos : dir -> $CHART_DIR name -> $CHART_NAME version -> $CHART_VERSION url -> $REPO_URL"

            helm repo add $REPO_NAME $REPO_URL
            helm repo update
            helm template "$CHART_NAME" "$REPO_NAME/$CHART_NAME" --version $CHART_VERSION > "target/${CHART_NAME}_manifest_pr.yaml"

            git checkout origin/main -- "$file"
            CHART_NAME=$(yq e 'select(document_index == 1).spec.chart.spec.chart' $file)
            CHART_VERSION=$(yq e 'select(document_index == 1).spec.chart.spec.version' $file)
            REPO_NAME=$(yq e 'select(document_index == 1).spec.chart.spec.sourceRef.name' $file)
            REPO_URL=$(yq e 'select(document_index == 0).spec.url' $file)

            echo "chart infos : dir -> $CHART_DIR name -> $CHART_NAME version -> $CHART_VERSION url -> $REPO_URL"

            helm repo add $REPO_NAME $REPO_URL
            helm repo update
            helm template "$CHART_NAME" "$REPO_NAME/$CHART_NAME" --version $CHART_VERSION > "source/${CHART_NAME}_manifest_main.yaml"
          done

      - name: Generate dyff on release
        id: dyff-helm
        uses: ixxeL-DevOps/gha-templates/.github/actions/dyff@main
        with:
          source: source/*_manifest_main.yaml
          target: target/*_manifest_pr.yaml

      - name: Comment on PR for helm dyff
        uses: actions/github-script@v7
        if: github.event_name == 'pull_request'
        env:
          DYFF_RESULTS: ${{ steps.dyff-helm.outputs.DYFF_RESULT }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `
            #### Dyff helm: \`chart helm dyff\`
            \`\`\`py
            ${process.env.DYFF_RESULTS}
            \`\`\`
            `;

            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: output
            })
